spring:
  application:
    name: Library

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/library
    username: postgres
    password: Olimp123
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

library:
  minAgeForRestrictedBooks: ${MIN_AGE_FOR_RESTRICTED_BOOK:18}
  maxBooksForBorrow: ${MAX_BOOKS_FOR_BORROW:2}

# Server configuration
server:
  port: 8081
  servlet:
    context-path: /book-library

springdoc:
  api-docs:
    path: /api-docs

info:
  java:
    version: ${java.version}
  application:
    name: Library
    description: The application provides the ability to create two entities (book and reader),
      as well as their interaction with each other.

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  exclude:
    - /**/swagger-ui/**
    - /**/api-docs/**
    - /**/actuator/**
