spring:
  application:
    name: Library

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/library
    username: postgres
    password: Olimp123
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
# Server configuration
server:
  port: 8081
  servlet:
    context-path: /book-library/api/v1

springdoc:
  api-docs:
    path: /api-docs

info:
  java:
    version: ${java.version}
  application:
    name: Library
    description: The application provides the ability to create two entities (book and reader),
      as well as their interaction with each other.

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.zalando.logbook: TRACE
