spring:
  application:
    name: Library

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/library
    username: postgres
    password: Olimp123
# Server configuration
server:
  port: 8081
  servlet:
    context-path: /book-library


