spring:
  application:
    name: Library
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: olimp123
# Server configuration
server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: INFO
  pattern:
    console: ' %msg%n '